//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniERPprojesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciGirisCikisLog
    {
        public int ID { get; set; }
        public int KullaniciID { get; set; }
        public System.DateTime GirisZamani { get; set; }
        public Nullable<System.DateTime> CikisZamani { get; set; }
        public Nullable<System.DateTime> SonPing { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
