//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniERPprojesi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MiniERPDBEntities6 : DbContext
    {
        public MiniERPDBEntities6()
            : base("name=MiniERPDBEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adresler> Adresler { get; set; }
        public virtual DbSet<Depolar> Depolar { get; set; }
        public virtual DbSet<DepoStok> DepoStok { get; set; }
        public virtual DbSet<Faturalar> Faturalar { get; set; }
        public virtual DbSet<Ilceler> Ilceler { get; set; }
        public virtual DbSet<Iller> Iller { get; set; }
        public virtual DbSet<Kategoriler> Kategoriler { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<Musteriler> Musteriler { get; set; }
        public virtual DbSet<Roller> Roller { get; set; }
        public virtual DbSet<SiparisKalemleri> SiparisKalemleri { get; set; }
        public virtual DbSet<Siparisler> Siparisler { get; set; }
        public virtual DbSet<StokHareketleri> StokHareketleri { get; set; }
        public virtual DbSet<Urunler> Urunler { get; set; }
        public virtual DbSet<v_adresler> v_adresler { get; set; }
        public virtual DbSet<v_depolar> v_depolar { get; set; }
        public virtual DbSet<v_faturalar> v_faturalar { get; set; }
        public virtual DbSet<v_musteriler> v_musteriler { get; set; }
        public virtual DbSet<v_siparisler> v_siparisler { get; set; }
        public virtual DbSet<v_stokhareketleri> v_stokhareketleri { get; set; }
        public virtual DbSet<v_urunler> v_urunler { get; set; }
        public virtual DbSet<v_depostok> v_depostok { get; set; }
        public virtual DbSet<v_siparisdetay> v_siparisdetay { get; set; }
        public virtual DbSet<KullaniciGirisCikisLog> KullaniciGirisCikisLog { get; set; }
        public virtual DbSet<v_kullanicilar> v_kullanicilar { get; set; }
    }
}
