//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniERPprojesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparisler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Siparisler()
        {
            this.Faturalar = new HashSet<Faturalar>();
            this.SiparisKalemleri = new HashSet<SiparisKalemleri>();
        }
    
        public int SiparisID { get; set; }
        public string SiparisNo { get; set; }
        public System.DateTime SiparisTarihi { get; set; }
        public int KullaniciID { get; set; }
        public int MusteriID { get; set; }
        public int AdresID { get; set; }
        public string SiparisDurumu { get; set; }
        public bool FaturalandiMi { get; set; }
    
        public virtual Adresler Adresler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faturalar> Faturalar { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Musteriler Musteriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisKalemleri> SiparisKalemleri { get; set; }
    }
}
