//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniERPprojesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokHareketleri
    {
        public int StokHareketID { get; set; }
        public int UrunID { get; set; }
        public int DepoID { get; set; }
        public int KullaniciID { get; set; }
        public Nullable<int> SiparisKalemID { get; set; }
        public int Miktar { get; set; }
        public decimal BirimFiyat { get; set; }
        public byte HareketTipi { get; set; }
        public System.DateTime HareketTarihi { get; set; }
        public bool IptalKaynakli { get; set; }
    
        public virtual Depolar Depolar { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual SiparisKalemleri SiparisKalemleri { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
