//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniERPprojesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_depolar
    {
        public int DepoID { get; set; }
        public string DepoAdi { get; set; }
        public int AdresID { get; set; }
        public string IlAdi { get; set; }
        public string IlceAdi { get; set; }
        public string Mahalle { get; set; }
        public string Sokak { get; set; }
        public string BinaNo { get; set; }
        public string DaireNo { get; set; }
        public string PostaKodu { get; set; }
        public string Adres { get; set; }
        public int OlusturanKullaniciID { get; set; }
        public string KullaniciAdi { get; set; }
    }
}
