//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniERPprojesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_faturalar
    {
        public int FaturaID { get; set; }
        public string FaturaNo { get; set; }
        public System.DateTime FaturaTarihi { get; set; }
        public int SiparisID { get; set; }
        public string SiparisNo { get; set; }
        public decimal ToplamTutar { get; set; }
        public string OdemeDurumu { get; set; }
        public string KullaniciAdi { get; set; }
    }
}
