//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniERPprojesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_siparisler
    {
        public int SiparisID { get; set; }
        public string SiparisNo { get; set; }
        public System.DateTime SiparisTarihi { get; set; }
        public string SiparisDurumu { get; set; }
        public bool FaturalandiMi { get; set; }
        public string MusteriAdi { get; set; }
    }
}
