//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniERPprojesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_siparisdetay
    {
        public int SiparisID { get; set; }
        public string SiparisNo { get; set; }
        public System.DateTime SiparisTarihi { get; set; }
        public string SiparisDurumu { get; set; }
        public bool FaturalandiMi { get; set; }
        public string MusteriAdi { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public string MusteriTuru { get; set; }
        public string IlAdi { get; set; }
        public string IlceAdi { get; set; }
        public string Mahalle { get; set; }
        public string Sokak { get; set; }
        public string BinaNo { get; set; }
        public string DaireNo { get; set; }
        public string PostaKodu { get; set; }
        public string Adres { get; set; }
        public string UrunAdi { get; set; }
        public string DepoAdi { get; set; }
        public int Adet { get; set; }
        public decimal BirimFiyat { get; set; }
        public bool IptalEdildi { get; set; }
    }
}
