//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniERPprojesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_stokhareketleri
    {
        public int StokHareketID { get; set; }
        public int DepoID { get; set; }
        public string DepoAdi { get; set; }
        public int UrunID { get; set; }
        public string UrunAdi { get; set; }
        public int Miktar { get; set; }
        public decimal BirimFiyat { get; set; }
        public Nullable<decimal> ToplamTutar { get; set; }
        public byte HareketTipi { get; set; }
        public string HareketTipiAdi { get; set; }
        public System.DateTime HareketTarihi { get; set; }
        public int KullaniciID { get; set; }
        public string KullaniciAdi { get; set; }
        public bool IptalKaynakli { get; set; }
    }
}
