//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniERPprojesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_urunler
    {
        public int UrunID { get; set; }
        public string UrunAdi { get; set; }
        public string Aciklama { get; set; }
        public decimal Fiyat { get; set; }
        public int KategoriID { get; set; }
        public string KategoriAdi { get; set; }
        public string ResimYolu { get; set; }
        public int OlusturanKullaniciID { get; set; }
    }
}
